<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Core\Fluent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="Whisper.net.Runtime.NoAvx" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
